name: 1-Checkout-Build-Artifact

on:
  workflow_dispatch:
  schedule:
    # Runs "Every Sunday" (see https://crontab.guru)
    - cron: '15 8 * * Sun'
jobs:
  Checkout-Build-Artifact:

    runs-on: windows-2022

# Checkout-Build-Artifact

    steps:
    - uses: actions/checkout@v3

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: Run msbuild
      run: |
          msbuild Verademo-dotnet.sln  
      
    - name: List folder contents for visual of folder contents
      run: |
         dir
   
    - name: Upload Application Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: VeraDemo-DotNet-App-Artifact
        path: Verademo-Dotnet/bin/
