name: 1-Checkout-Build-Artifact

on:
  workflow_dispatch:
  schedule:
    # Runs "Every Sunday" (see https://crontab.guru)
    - cron: '15 8 * * Sun'
jobs:
  Checkout-Build-Artifact:

    runs-on: windows-2022

# Checkout-Build-Artifact

    steps:
    - uses: actions/checkout@v3

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: Run msbuild
      run: |
          msbuild Verademo-dotnet.sln  
      
    - name: List folder contents for visual of folder contents
      run: |
         ls -la
   
    - name: Upload Application Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: VeraDemo-DotNet-App-Artifact
        path: Verademo-Dotnet/bin/
        
  Dockerize-PublishImage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
# Dockerize-Publish
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Ubuntu MSSQL Docker Image Dependency
      run: docker pull mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04      

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: veracodedemolabs/verademo-dotnet-gh:latest
